/* Built-in customer reviews (merged with any reviews saved in the browser) */
var SEED_REVIEWS = [
  /* Strike Freedom */
  {
    id: 'seed-1-1',
    productId: '1',
    rating: 5,
    author: 'Miguel R.',
    title: 'Wings look incredible panel lined',
    body: 'Took me two weekends but the dragoons are worth it. Fit is tight on a few wing connectors—dry-fit everything first. Finished with matte top coat and it photographs beautifully.',
    date: '2025-11-08T10:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-1-2',
    productId: '1',
    rating: 5,
    author: 'Patricia L.',
    title: 'Best RG in my collection',
    body: 'Articulation is crazy good for the size. Beam sabers and rifles hold firm in dynamic poses. Only nitpick is a couple of tiny stickers on the waist—decals would have been nicer.',
    date: '2025-09-22T14:30:00.000Z',
    seed: true,
  },
  {
    id: 'seed-1-3',
    productId: '1',
    rating: 4,
    author: 'KenjiBuilds',
    title: 'Solid kit, busy build',
    body: 'Not a beginner project because of the backpack. Instructions are clear though. Shipped fast from Gunpla Hobby PH, no bent runners.',
    date: '2025-08-03T09:15:00.000Z',
    seed: true,
  },
  {
    id: 'seed-1-4',
    productId: '1',
    rating: 5,
    author: 'Angelo V.',
    title: 'Dragoons stay put',
    body: 'Used a tiny dot of poster putty on the backpack connectors for extra security on the shelf. Color accuracy is spot on for Destiny fans. Would buy again from this shop.',
    date: '2025-06-21T16:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-1-5',
    productId: '1',
    rating: 4,
    author: 'Carmen D.',
    title: 'Worth the desk space',
    body: 'Larger footprint than my Qan[T] but the silhouette is iconic. Took care nubbing the wing edges—worth the effort. Manual is dense but logical.',
    date: '2025-04-10T11:30:00.000Z',
    seed: true,
  },
  /* OO Qan[T] */
  {
    id: 'seed-2-1',
    productId: '2',
    rating: 5,
    author: 'Andrea S.',
    title: 'Clean lines out of the box',
    body: 'The white armor pops after a light panel wash. GN sword bits are fiddly but stay on once clipped. Great desk piece next to my 00 Raiser.',
    date: '2025-10-14T11:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-2-2',
    productId: '2',
    rating: 4,
    author: 'Dale M.',
    title: 'Good value RG',
    body: 'Frame is stiff and poses well. Had to sand one hip joint slightly for smoother movement. Overall happy with the purchase.',
    date: '2025-07-19T16:45:00.000Z',
    seed: true,
  },
  {
    id: 'seed-2-3',
    productId: '2',
    rating: 4,
    author: 'Hannah T.',
    title: 'Sharp green accents',
    body: 'Stickers need patience on the chest vents. Recommend tweezers and setting solution. Looks amazing under LED shelf lighting.',
    date: '2025-05-28T08:20:00.000Z',
    seed: true,
  },
  {
    id: 'seed-2-4',
    productId: '2',
    rating: 5,
    author: 'Luis G.',
    title: 'GN bits look great painted',
    body: 'Did a light metallic dry brush on the sword bits. Inner frame is sturdy—no floppy ankles. Packaging was secure, all runners accounted for.',
    date: '2025-04-12T13:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-2-5',
    productId: '2',
    rating: 4,
    author: 'Yuki M.',
    title: 'Clean UC-adjacent aesthetic',
    body: 'White armor shows finger oil easily—wash hands often or wear gloves. Posing for the rifle stance took a few tries but stays put. Solid RG overall.',
    date: '2025-03-05T09:45:00.000Z',
    seed: true,
  },
  /* Wing Zero Custom EW */
  {
    id: 'seed-3-1',
    productId: '3',
    rating: 5,
    author: 'Jerome C.',
    title: 'Shelf presence is unreal',
    body: 'Wingspan is huge for RG—make sure you have space. Twin buster rifle is well balanced. Did a light weathering on panel lines and it still looks elegant.',
    date: '2025-12-01T13:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-3-2',
    productId: '3',
    rating: 5,
    author: 'Claire W.',
    title: 'EW proportions done right',
    body: 'Feathers on the wings are separate parts so you can paint before assembly. No major nubs visible after cleanup. My favorite Wing kit so far.',
    date: '2025-09-05T10:30:00.000Z',
    seed: true,
  },
  {
    id: 'seed-3-3',
    productId: '3',
    rating: 4,
    author: 'Rico P.',
    title: 'Display with a stand',
    body: 'Top-heavy with wings fully open—use an action base. Build was straightforward, just take your time on the shoulder feathers.',
    date: '2025-06-17T18:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-3-4',
    productId: '3',
    rating: 5,
    author: 'Noah F.',
    title: 'Twin buster rifle is crisp',
    body: 'Snapped the rifles together in one sitting—no glue needed. Wing joints hold spread poses overnight. One of my best purchases this year.',
    date: '2025-05-03T14:20:00.000Z',
    seed: true,
  },
  {
    id: 'seed-3-5',
    productId: '3',
    rating: 4,
    author: 'Isabel R.',
    title: 'Plan your shelf height',
    body: 'Vertical clearance matters with wings up. Feather parts are thin—nip close. Still a five-star kit minus the space requirement.',
    date: '2025-03-22T10:00:00.000Z',
    seed: true,
  },
  /* Unicorn */
  {
    id: 'seed-4-1',
    productId: '4',
    rating: 5,
    author: 'Vincent A.',
    title: 'Engineering is top tier',
    body: 'Transformation works if you follow the manual step by step. Psycho-frame under UV light is a nice touch. Worth every peso for UC fans.',
    date: '2025-11-20T09:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-4-2',
    productId: '4',
    rating: 5,
    author: 'Elaine D.',
    title: 'Flagship RG for a reason',
    body: 'Parts count is high but runners are organized well. V-fin and face sculpt are crisp. Took breaks between phases and enjoyed the whole build.',
    date: '2025-08-30T15:20:00.000Z',
    seed: true,
  },
  {
    id: 'seed-4-3',
    productId: '4',
    rating: 5,
    author: 'Marcus T.',
    title: 'Destroy mode display',
    body: 'Built in unicorn mode first, then tried destroy—transformation is smoother after the first cycle. Magnificent on a mirrored base.',
    date: '2025-07-12T12:10:00.000Z',
    seed: true,
  },
  {
    id: 'seed-4-4',
    productId: '4',
    rating: 4,
    author: 'Sofia G.',
    title: 'Advanced but rewarding',
    body: 'Not my first RG and still learned new tricks. A few tiny parts—use a parts tray. Authentic Bandai as advertised.',
    date: '2025-04-25T11:45:00.000Z',
    seed: true,
  },
  {
    id: 'seed-4-5',
    productId: '4',
    rating: 5,
    author: 'James H.',
    title: 'Psycho-frame sells the kit',
    body: 'Hit the green parts with a UV pen and it glows nicely in a display case. Transformation manual diagrams are clear if you go slow. Premium RG experience.',
    date: '2025-03-14T08:30:00.000Z',
    seed: true,
  },
  /* RX-78-2 */
  {
    id: 'seed-5-1',
    productId: '5',
    rating: 5,
    author: 'Ben K.',
    title: 'Classic done modern',
    body: 'Great intro to RG if you grew up on HG. Core fighter gimmick is fun. Colors are accurate; I only added a bit of chipping on the shield.',
    date: '2025-10-02T08:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-5-2',
    productId: '5',
    rating: 4,
    author: 'Nina F.',
    title: 'Nostalgic and fun',
    body: 'Build time was shorter than my Sinanju kit. Beam rifle hand is snug. Good gift for someone getting into Gunpla.',
    date: '2025-07-08T14:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-5-3',
    productId: '5',
    rating: 5,
    author: 'OldSchoolBuilder',
    title: 'Still holds up',
    body: 'Bought two—one straight build, one custom paint. Both kits had clean mold lines. Fast shipping to Cebu.',
    date: '2025-05-15T17:30:00.000Z',
    seed: true,
  },
  {
    id: 'seed-5-4',
    productId: '5',
    rating: 4,
    author: 'Rhea C.',
    title: 'Great starter RG',
    body: 'First Real Grade for my nephew—he finished the legs in one afternoon. Beam saber hilts are tiny; adult supervision helps. Authentic kit, fair price.',
    date: '2025-04-08T15:10:00.000Z',
    seed: true,
  },
  {
    id: 'seed-5-5',
    productId: '5',
    rating: 5,
    author: 'Victor L.',
    title: 'OG Gundam energy',
    body: 'Panel lined with grey and it pops. Core fighter locks in without wobble. Arrived two days after ordering—well packed in bubble wrap.',
    date: '2025-02-19T12:00:00.000Z',
    seed: true,
  },
  /* Build Strike Full Package */
  {
    id: 'seed-6-1',
    productId: '6',
    rating: 4,
    author: 'Jake H.',
    title: 'Lots of accessories',
    body: 'Support gear and weapons mean more build time but great variety for photos. Some blue parts needed light sanding on nub marks.',
    date: '2025-09-18T10:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-6-2',
    productId: '6',
    rating: 5,
    author: 'Lyka M.',
    title: 'Build Fighters fan approved',
    body: 'Clear parts on the beam effects look great with gloss coat. Frame is color-coded which helps beginners. Happy with this shop.',
    date: '2025-08-01T13:25:00.000Z',
    seed: true,
  },
  {
    id: 'seed-6-3',
    productId: '6',
    rating: 4,
    author: 'Tom V.',
    title: 'Busy but colorful',
    body: 'Full package lives up to the name—budget extra evenings. Stickers on the booster are the trickiest part.',
    date: '2025-06-09T09:40:00.000Z',
    seed: true,
  },
  {
    id: 'seed-6-4',
    productId: '6',
    rating: 5,
    author: 'Sam P.',
    title: 'Weapon loadout is fun',
    body: 'Swapped configs for photos—plasma cannon and rifle both look sharp. Blue frame contrasts nicely with the white armor. Full package is the way to go.',
    date: '2025-05-20T11:35:00.000Z',
    seed: true,
  },
  {
    id: 'seed-6-5',
    productId: '6',
    rating: 4,
    author: 'Denise A.',
    title: 'Sticker heavy but doable',
    body: 'Set aside an evening just for decals on the backpack. Once done, the kit really comes alive. Good for builders who like accessories.',
    date: '2025-03-30T09:00:00.000Z',
    seed: true,
  },
  /* Zeta */
  {
    id: 'seed-7-1',
    productId: '7',
    rating: 5,
    author: 'Rafael O.',
    title: 'Transformation actually works',
    body: 'Surprised how stable waverider mode is. Read the transformation section twice before starting. Waist is tight in MS mode but loosens slightly after a few cycles.',
    date: '2025-10-25T11:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-7-2',
    productId: '7',
    rating: 4,
    author: 'Grace Y.',
    title: 'For experienced builders',
    body: 'My third RG and still challenging. No missing parts. Recommend nippers and sandpaper. Looks dynamic in flight pose.',
    date: '2025-07-30T16:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-7-3',
    productId: '7',
    rating: 4,
    author: 'Ian P.',
    title: 'Worth the learning curve',
    body: 'Some seams show in waverider mode if you rush. Take time on the hip locks. Finished product is a conversation starter.',
    date: '2025-05-02T12:50:00.000Z',
    seed: true,
  },
  {
    id: 'seed-7-4',
    productId: '7',
    rating: 5,
    author: 'Owen T.',
    title: 'Waverider mode surprised me',
    body: 'Expected floppy wings—locks are better than HG Zeta I built years ago. MS mode ankles are stiff in a good way. Challenging but fair for RG.',
    date: '2025-04-16T10:25:00.000Z',
    seed: true,
  },
  {
    id: 'seed-7-5',
    productId: '7',
    rating: 3,
    author: 'Liza N.',
    title: 'Not for first-time RG',
    body: 'Transformation left small stress marks on one hip piece—still holds. Would recommend watching a build video first. Finished kit still looks amazing on display.',
    date: '2025-02-28T14:40:00.000Z',
    seed: true,
  },
  /* Full Burnern */
  {
    id: 'seed-8-1',
    productId: '8',
    rating: 5,
    author: 'Chloe B.',
    title: 'Sleek out of the box',
    body: 'Color separation is excellent—minimal painting needed. Boosters click in firmly. Great for Build Fighters shelf theme.',
    date: '2025-11-11T09:30:00.000Z',
    seed: true,
  },
  {
    id: 'seed-8-2',
    productId: '8',
    rating: 5,
    author: 'Dex L.',
    title: 'Underrated RG',
    body: 'Poses like the anime launch scenes. Panel lines are deep enough for wash. Arrived well packed, no cracked v-fin.',
    date: '2025-08-14T15:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-8-3',
    productId: '8',
    rating: 4,
    author: 'Monica R.',
    title: 'Quick satisfying build',
    body: 'Finished in a weekend compared to my Zeta. Stickers on yellow chest need care. Still recommend for BF fans.',
    date: '2025-06-22T10:15:00.000Z',
    seed: true,
  },
  {
    id: 'seed-8-4',
    productId: '8',
    rating: 4,
    author: 'Eric B.',
    title: 'Great dynamic poses',
    body: 'Thrust vectoring fins angle nicely for launch poses. Yellow chest needed panel wash to define details. Runner layout made subassembly easy.',
    date: '2025-05-07T16:50:00.000Z',
    seed: true,
  },
  {
    id: 'seed-8-5',
    productId: '8',
    rating: 5,
    author: 'Aisha K.',
    title: 'Underrated shelf piece',
    body: 'Pairs well with my Build Strike on the same shelf. No loose joints after a month displayed. Gunpla Hobby PH included all runners—no duplicates missing.',
    date: '2025-03-18T08:15:00.000Z',
    seed: true,
  },
  /* Sinanju */
  {
    id: 'seed-9-1',
    productId: '9',
    rating: 5,
    author: 'Adrian N.',
    title: 'Premium feel in RG scale',
    body: 'Gold trim stickers are tedious but the result is regal. Shield is heavy—pose with both hands. Authentic decals included.',
    date: '2025-12-05T08:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-9-2',
    productId: '9',
    rating: 5,
    author: 'Bianca J.',
    title: 'Stunning red plastic',
    body: 'No need to paint the main armor if you panel line. Rifle detail is insane for 1/144. My display centerpiece now.',
    date: '2025-09-29T13:40:00.000Z',
    seed: true,
  },
  {
    id: 'seed-9-3',
    productId: '9',
    rating: 4,
    author: 'Harold S.',
    title: 'Big personality, small scale',
    body: 'Shoulder spikes are sharp—be careful trimming. Slight gap on backpack mount until tightened. Overall 9/10 build experience.',
    date: '2025-07-03T19:20:00.000Z',
    seed: true,
  },
  {
    id: 'seed-9-4',
    productId: '9',
    rating: 5,
    author: 'Carlo M.',
    title: 'Gold trim pops with top coat',
    body: 'Sealed stickers with flat coat so edges do not peel. Shield decals aligned with tweezers. Imposing next to my RX-78—scale feels right.',
    date: '2025-06-11T12:30:00.000Z',
    seed: true,
  },
  {
    id: 'seed-9-5',
    productId: '9',
    rating: 4,
    author: 'Helen W.',
    title: 'Sticker marathon but worth it',
    body: 'Budget an extra evening for the gold trim alone. Plastic quality is excellent—no swirls on the red. Rifle scope detail is chef kiss for 1/144.',
    date: '2025-04-02T17:00:00.000Z',
    seed: true,
  },
  /* God Gundam */
  {
    id: 'seed-10-1',
    productId: '10',
    rating: 5,
    author: 'Kyle D.',
    title: 'Perfect for martial arts poses',
    body: 'Core Lander gimmick is nostalgic. Orange and red plastics are vibrant. Fingers articulate well for Shining Finger style poses.',
    date: '2025-11-02T12:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-10-2',
    productId: '10',
    rating: 5,
    author: 'Mei L.',
    title: 'G Gundam fans rejoice',
    body: 'Chest fire decals look hot with gloss. Build was smoother than expected. Pair with an action base for kicking poses.',
    date: '2025-08-26T11:10:00.000Z',
    seed: true,
  },
  {
    id: 'seed-10-3',
    productId: '10',
    rating: 4,
    author: 'Paolo E.',
    title: 'Bold and fun',
    body: 'Some gold parts are stickers not foil—plan a top coat. Still looks fantastic on the shelf next to my Wing kit.',
    date: '2025-06-01T14:55:00.000Z',
    seed: true,
  },
  {
    id: 'seed-10-4',
    productId: '10',
    rating: 5,
    author: 'Trisha W.',
    title: 'Great first G Gundam kit',
    body: 'Instructions highlight pose ideas which helped. All joints stiff enough to hold kicks. Will order another RG from this store.',
    date: '2025-04-18T09:00:00.000Z',
    seed: true,
  },
  {
    id: 'seed-10-5',
    productId: '10',
    rating: 4,
    author: 'Jonas R.',
    title: 'Super poseable torso',
    body: 'Waist twist is better than my older HG God. Cloak parts optional but add flair. Orange plastic is vivid under warm room lighting.',
    date: '2025-03-09T13:20:00.000Z',
    seed: true,
  },
];
